### ISSUE TITLE
Jawaban nomor 1 kurang tepat

### ISSUE THREAD

**Issue by achmadk** [aisyahningsi/learn-javascript#1]
Permisi, Mbak @aisyahningsi . Terima kasih sudah menjawab pertanyaannya.

Jawaban nomor pertama bisa benar jika pertanyaannya `Apa yang terjadi bila sebuah variabel dideklarasi ulang menggunakan let?`

```js
let value = 'Name'
let value = true
```

Maksud pertanyaan saya yang pertama `Apa yang terjadi bila sebuah variabel let diganti nilainya. Entah digantinya tetap menggunakan tipe data yang sama, maupun diganti ke tipe data lain?`

contohnya
```js
let value = 'Name'
value = true // `let` tidak dituliskan kembali 
```

**Comment by aisyahwsn** [comment]
Baik mas @achmadk, jawaban sudah saya update. 
https://github.com/aisyahningsi/learn-javascript/blob/master/Screen%20Shot%202019-05-01%20at%2011.28.00.png

**Comment by achmadk** [comment]
Oke, jawabannya sudah bener. saya close issue-nya.
